Add Linea Chain
Certora/Quorum pull request #53
Opened 2024-12-29 15:54 UTC by nivcertora

https://certora.atlassian.net/browse/CERT-7800

Ready for review but still waiting for @itay-certora proposal example for testing.

2024-12-29 16:25 UTC, yoav-el-certora requested changes
Lets put this on hold until @itay-certora will provide a proposal for regression testing

2024-12-30 08:01 UTC, yoav-el-certora approved these changes
Open a follow-up ticket to add Linea regression test, assign @itay-certora until he provides a proposal

2024-12-30 09:27 UTC, liav-certora commented on .github/workflows/CI.yml
> +        (github.event_name == 'pull_request' &&
Adding another "Single Comment" to test CI trigger

2024-12-30 09:28 UTC, liav-certora submitted a review, later dismissed

2024-12-30 09:37 UTC, liav-certora commented on .github/workflows/CI.yml
> +        (github.event_name == 'pull_request' &&
Adding another "Single Comment" while PR is approved.

2024-12-30 09:45 UTC, yoav-el-certora commented on .github/workflows/CI.yml
> +        (github.event_name == 'pull_request' &&
```suggestion
        (github.event_name == 'pull_request_review' && github.event.review.state != 'commented') 
```

2024-12-30 09:50 UTC, yoav-el-certora commented on Quorum/tests/blockchain_api_test.py
> +    'chain, contract_address',
Comment without approval

2024-12-30 09:51 UTC, yoav-el-certora commented on Quorum/apis/block_explorers/chains_api.py
> +        Chain.ZK: 324,
Comment

2024-12-30 09:53 UTC, yoav-el-certora approved these changes

2024-12-30 10:01 UTC, merged