Add setup for the tool usage
Certora/Quorum pull request #59
Opened 2024-12-31 14:39 UTC by nivcertora

https://certora.atlassian.net/browse/CERT-7888

2025-01-01 12:05 UTC, yoav-el-certora commented on Quorum/utils/config.py
> +
Too many spaces

2025-01-01 12:07 UTC, yoav-el-certora commented on README.md
> +SetupQuorum [working_directory]
```suggestion
setupQuorum [working_directory]
```

2025-01-01 12:08 UTC, yoav-el-certora commented on README.md
> +SetupQuorum ./my_quorum_project
```suggestion
setupQuorum ./my_quorum_project
```

2025-01-01 12:08 UTC, yoav-el-certora commented on README.md
> +  - `Readme.md`
```suggestion
  - `README.md`
```

2025-01-01 12:08 UTC, yoav-el-certora commented on README.md
> +- Provide guidance through comments within the configuration files and detailed Readme file to help you properly configure Quorum.
```suggestion
- Provide guidance through comments within the configuration files, and a detailed README file to help you properly configure Quorum.
```

2025-01-01 12:09 UTC, yoav-el-certora commented on README.md
> +   Edit the `.env` file to include your actual API keys and desired paths:
Please explain this is not mandatory and can be configured in system variables.

2025-01-01 12:10 UTC, yoav-el-certora commented on README.md
> +   - **`Readme.md`**: Follow the included guide to understand installation, configuration, available flags, and the checks performed by Quorum.
```suggestion
   - **`README.md`**: Follow the included guide to understand installation, configuration, available flags, and the checks performed by Quorum.
```

2025-01-01 12:13 UTC, yoav-el-certora commented on Quorum/templates/Readme.md
Please rename to README

2025-01-01 12:18 UTC, yoav-el-certora commented on Quorum/templates/Readme.md
> +This file contains environment variables that need to be set for the project to run.
```suggestion
This file contains environment variables that needs to be set for the project to run.
```

2025-01-01 12:19 UTC, yoav-el-certora commented on Quorum/templates/Readme.md
> +3. `.env` set the required environment variables.
```suggestion
3. Set the required environment variables at `.env`.
```

2025-01-01 12:20 UTC, yoav-el-certora commented on Quorum/templates/Readme.md
> +By following these instructions, you will ensure that the Quorum project is correctly configured and ready to use.
```suggestion
By following these instructions, you will ensure Quorum is correctly configured and ready to use.
```

2025-01-01 12:22 UTC, yoav-el-certora commented on Quorum/entry_points/setup_quorum.py
> +    Initializes a Quorum environment by copying template files to the specified directory.
```suggestion
    Initializes Quorum environment by copying template files to the specified directory.
```

2025-01-01 12:24 UTC, yoav-el-certora commented on Quorum/entry_points/setup_quorum.py
> +        default=Path.cwd(),
Should we append a working dir name to cwd?
Something like `Path.cwd() / 'quorum_repo'`

2025-01-01 13:06 UTC, nivcertora commented on Quorum/utils/config.py
> +
Done

2025-01-01 13:15 UTC, nivcertora commented on README.md
> +   Edit the `.env` file to include your actual API keys and desired paths:
Done

2025-01-01 13:15 UTC, nivcertora commented on README.md
> +   - **`Readme.md`**: Follow the included guide to understand installation, configuration, available flags, and the checks performed by Quorum.
Done

2025-01-01 13:16 UTC, nivcertora commented on Quorum/templates/Readme.md
Done

2025-01-01 13:18 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +        default=Path.cwd(),
done

2025-01-01 15:23 UTC, yoav-el-certora commented on Quorum/templates/Readme.md
Did you forgot to delete this file?

2025-01-01 22:48 UTC, liav-certora requested changes
Minor naming changes to avoid future confusions.

I think using json5 is unnecessary since you are using it because of the templates, but: 
1. You shouldn't open these template files, just copy them for the user (correct me if I'm wrong).
2. The user has to configure these templates either and they will most likely remove the comments because the files are formatted as json and their IDE will tell them there are errors.
This introduces another third party dependency which we don't need.

Repo organization looks great. Setup tool implementation is clean.

2025-01-01 22:48 UTC, liav-certora commented on Quorum/apis/price_feeds/price_feed_utils.py
> +import json5 as json
Please change that to simply `import json5`. I'm afraid that down the line it will get confusing because these 2 packages do act a little bit differently in certain things (as you saw).

2025-01-01 22:48 UTC, liav-certora commented on Quorum/auto_report/aave_tags.py
> +import json5 as json
Same

2025-01-01 22:48 UTC, liav-certora commented on Quorum/checks/check.py
> +import json5 as json
Same

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/check_proposal.py
> +import json5 as json
Same

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/setup_quorum.py
> +import Quorum.utils.pretty_printer as pp
Blank line above please :)

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/setup_quorum.py
> +def get_working_directory() -> Path:
Please change name to `parse_args`. I know that this function only returns the directory for Quorum but it became kind of an unwritten convention over all of our command line tools that we call `parse_args` for parsing the arguments.

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/setup_quorum.py
> +        '--working_dir',
I suggest change the name to `--target_dir` or something similar. "working_dir" is too confusing with the "current working directory" imo.

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/setup_quorum.py
> +    target_dir = working_dir.resolve()
Hey you actually named it "target_dir" here lol

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/setup_quorum.py
> +    template_files = ['ground_truth.json', 'execution.json', '.env.example', 'README.md']
I suggest simply getting everything from the templates dir and not making it hard-coded.

2025-01-01 22:48 UTC, liav-certora commented on Quorum/entry_points/setup_quorum.py
> +        pp.pretty_print(f"Copied {file_name} to {dest}", pp.Colors.SUCCESS)
I checked and if `.env` is in a subdirectory it won't be found automatically so you can rename `.env.example` to `.env` without worrying. With that you can just use `shutil.copytree` instead of the whole for loop but that means everything will be overridden, unlike how you skip existing files. Which I actually think can be better because if a user messes his directory or one of the files he can easily just run this tool again.
You have the option, whatever you prefer.

2025-01-01 22:48 UTC, liav-certora commented on Quorum/tests/expected/test_auto_report/v3-132.md
I already told you that I think changing the expected file instead of changing the code is principally wrong. Yes even for the smallest of differences like ", especially when the fix involves adding 3 words.

2025-01-01 22:48 UTC, liav-certora commented on Quorum/tests/test_price_feed_providers.py
> +import json5 as json
Same

2025-01-01 22:48 UTC, liav-certora commented on Quorum/tests/test_source_code.py
> +import json5 as json
Same

2025-01-01 22:48 UTC, liav-certora commented on Quorum/utils/config_loader.py
> +import json5 as json
Same

2025-01-02 05:59 UTC, nivcertora commented
> Minor naming changes to avoid future confusions.
> 
> I think using json5 is unnecessary since you are using it because of the templates, but:
> 
> 1. You shouldn't open these template files, just copy them for the user (correct me if I'm wrong).
> 2. The user has to configure these templates either and they will most likely remove the comments because the files are formatted as json and their IDE will tell them there are errors.
>    This introduces another third party dependency which we don't need.
> 
> Repo organization looks great. Setup tool implementation is clean.

I honestly don't see any difference in terms of using json5 over json. as long as it dosent introduce any issues its preferred to be used just in case the user will leave comments in the templates instead of crashing the tool. and most users use sublime text and not a really ide for just for general knowlage.

2025-01-02 06:01 UTC, nivcertora commented on Quorum/apis/price_feeds/price_feed_utils.py
> +import json5 as json
The difference between them is agnostic, if it will cause any issue in the future we can change it. for now, i prefer it to be called json instead of a variable with number name just for apperance.

2025-01-02 06:01 UTC, nivcertora commented on Quorum/auto_report/aave_tags.py
> +import json5 as json
Same

2025-01-02 06:01 UTC, nivcertora commented on Quorum/checks/check.py
> +import json5 as json
same

2025-01-02 06:01 UTC, nivcertora commented on Quorum/entry_points/check_proposal.py
> +import json5 as json
same

2025-01-02 06:03 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +import Quorum.utils.pretty_printer as pp
Done

2025-01-02 06:04 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +def get_working_directory() -> Path:
I prefer a more accurate name here. if ever we need to add more argument here ill re name it to parse args

2025-01-02 06:04 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +        '--working_dir',
Working dir is more accurate to the user as its going to be the directory he going work from.

2025-01-02 06:05 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +    target_dir = working_dir.resolve()
Here it serves as a target for the copy file therefore the new variable name is introduced which adds additional clarity for the code readable. (For us not the user).

2025-01-02 06:10 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +    template_files = ['ground_truth.json', 'execution.json', '.env.example', 'README.md']
Done, good one

2025-01-02 06:12 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +        pp.pretty_print(f"Copied {file_name} to {dest}", pp.Colors.SUCCESS)
I prefer the current state, and also i would suggest to not upload a .env to the repo.

2025-01-02 06:13 UTC, nivcertora commented on Quorum/tests/expected/test_auto_report/v3-132.md
I understand your point and yet if the output is improved i am not seeing any issue with modify the test for the better output.

2025-01-02 06:13 UTC, nivcertora commented on Quorum/tests/test_price_feed_providers.py
> +import json5 as json
same

2025-01-02 06:13 UTC, nivcertora commented on Quorum/tests/test_source_code.py
> +import json5 as json
same

2025-01-02 06:13 UTC, nivcertora commented on Quorum/utils/config_loader.py
> +import json5 as json
same

2025-01-02 06:53 UTC, yoav-el-certora commented on Quorum/entry_points/setup_quorum.py
> +        pp.pretty_print(f"Copied {file_name} to {dest}", pp.Colors.SUCCESS)
```suggestion
    template_files = [f for f in templates_dir.iterdir() if f.is_file()]

    for file in template_files:
        dest = target_dir / '.env' if file.name == '.env.example' else target_dir / file.name

        if dest.exists():
            pp.pretty_print(f"File exists: {dest}. Skipping.", pp.Colors.WARNING)
            continue

        shutil.copy(file, dest)
        pp.pretty_print(f"Copied {file.name} to {dest}", pp.Colors.SUCCESS)
```

Last one since functionality changed

2025-01-02 06:53 UTC, yoav-el-certora commented on Quorum/entry_points/setup_quorum.py
> +        if dest.exists():
Do we want maybe to override if exists?

2025-01-02 06:54 UTC, yoav-el-certora approved these changes

2025-01-02 08:06 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +        pp.pretty_print(f"Copied {file_name} to {dest}", pp.Colors.SUCCESS)
Not sure its going to work for the .env check. so ill keep it for now

2025-01-02 08:07 UTC, nivcertora commented on Quorum/entry_points/setup_quorum.py
> +        if dest.exists():
I prefer to be safe than sorry here and avoid delete user files if not necessary, we can always change it later by request from the client

2025-01-02 08:07 UTC, merged

2025-01-02 08:34 UTC, yoav-el-certora commented on Quorum/entry_points/setup_quorum.py
> +        pp.pretty_print(f"Copied {file_name} to {dest}", pp.Colors.SUCCESS)
It will work as you iterate on absolute files